### ISSUE TITLE
при первом запуске выскочило куча ошибок 

### ISSUE THREAD

**Issue by Leepey** [Muhammadali-Akbarov/fastgram#1]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Admin\PycharmProjects\fastgram-main\.venv\Lib\site-packages\uvicorn\_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\Admin\PycharmProjects\fastgram-main\.venv\Lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\fastgram-main\.venv\Lib\site-packages\uvicorn\server.py", line 69, in serve
    config.load()
  File "C:\Users\Admin\PycharmProjects\fastgram-main\.venv\Lib\site-packages\uvicorn\config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\fastgram-main\.venv\Lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "C:\Users\Admin\PycharmProjects\fastgram-main\.venv\Lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Admin\PycharmProjects\fastgram-main\main.py", line 10, in <module>
    from app.bot.presentation import router
  File "C:\Users\Admin\PycharmProjects\fastgram-main\app\bot\presentation\router\__init__.py", line 4, in <module>
    from .webhook.update import path as updates_route # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\fastgram-main\app\bot\presentation\router\webhook\update.py", line 4, in <module>
    from app.bot.presentation import handler
  File "C:\Users\Admin\PycharmProjects\fastgram-main\app\bot\presentation\handler\__init__.py", line 4, in <module>
    from .webhook import updates # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\fastgram-main\app\bot\presentation\handler\webhook\__init__.py", line 4, in <module>
    from .updates import updates_hander# noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\fastgram-main\app\bot\presentation\handler\webhook\updates.py", line 4, in <module>
    from app.bot.services.external.aiogram import bot
  File "C:\Users\Admin\PycharmProjects\fastgram-main\app\bot\services\external\aiogram\__init__.py", line 7, in <module>
    from app.bot.services.external.aiogram import middleware
  File "C:\Users\Admin\PycharmProjects\fastgram-main\app\bot\services\external\aiogram\middleware\__init__.py", line 4, in <module>
    from .lang import language_middleware as language  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\fastgram-main\app\bot\services\external\aiogram\middleware\lang.py", line 7, in <module>
    from app.bot.controllers import controller
  File "C:\Users\Admin\PycharmProjects\fastgram-main\app\bot\controllers\__init__.py", line 5, in <module>
    from .controller import * # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\fastgram-main\app\bot\controllers\controller.py", line 7, in <module>
    from app.bot import repositories
  File "C:\Users\Admin\PycharmProjects\fastgram-main\app\bot\repositories\__init__.py", line 5, in <module>
    from .db import repository # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\fastgram-main\app\bot\repositories\db.py", line 8, in <module>
    from app.bot.services.external.redis import redis_client
  File "C:\Users\Admin\PycharmProjects\fastgram-main\app\bot\services\external\redis\__init__.py", line 4, in <module>
    import redis
  File "C:\Users\Admin\PycharmProjects\fastgram-main\.venv\Lib\site-packages\redis\__init__.py", line 1, in <module>
    from redis.client import Redis, StrictRedis
  File "C:\Users\Admin\PycharmProjects\fastgram-main\.venv\Lib\site-packages\redis\client.py", line 13, in <module>
    from redis.connection import (ConnectionPool, UnixDomainSocketConnection,
  File "C:\Users\Admin\PycharmProjects\fastgram-main\.venv\Lib\site-packages\redis\connection.py", line 2, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'

**Comment by Muhammadali-Akbarov** [comment]
```pip install setuptools``` and u can use docker as well ```docker-compose up --build```
